# Generated by Django 5.2.13 on 2026-04-21 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='venda',
            field=models.ForeignKey(blank=True, db_column='FK_id_venda', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='marketplace.anuncio'),
        ),
        migrations.AddField(
            model_name='produto',
            name='reserva',
            field=models.ForeignKey(blank=True, db_column='FK_id_reserva', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='inventory.reserva'),
        ),
        migrations.AddField(
            model_name='produto',
            name='unidade',
            field=models.ForeignKey(db_column='FK_id_unidade', on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='inventory.unidademedida'),
        ),
        migrations.AddIndex(
            model_name='mvtoproduto',
            index=models.Index(fields=['produto', '-dt_entrada'], name='MVTO_PRODUT_FK_id_p_e58897_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['empresa', '-data_registro'], name='PRODUTO_FK_id_e_0b8cd4_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['categoria_residuo'], name='PRODUTO_FK_id_c_a51f30_idx'),
        ),
    ]
